language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - "10"
  - "12"

before_install:
  # Install latest Yarn.
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --frozen-lockfile

script:
  - yarn ci

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_deploy:
  - cd pkg
deploy:
  - provider: npm
    skip_cleanup: true
    email: uma.karimov@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: false
      node_js: "10"
      branch: master
      repo: umidbekkarimov/utility-hooks
